execute if entity @s[scores={3layer=1}] run tp @s ~10 ~ ~
execute if entity @s[scores={3layer=2}] run tp @s ~20 ~ ~
execute if entity @s[scores={3layer=3}] run tp @s ~30 ~ ~
execute if entity @s[scores={3layer=4}] run tp @s ~40 ~ ~
execute if entity @s[scores={3layer=5}] run tp @s ~50 ~ ~
execute if entity @s[scores={3layer=6}] run tp @s ~60 ~ ~
execute if entity @s[scores={3layer=7}] run tp @s ~70 ~ ~
execute if entity @s[scores={3layer=8}] run tp @s ~80 ~ ~
execute if entity @s[scores={3layer=9}] run tp @s ~90 ~ ~
execute if entity @s[scores={3layer=10}] run tp @s ~100 ~ ~
execute if entity @s[scores={3layer=11}] run tp @s ~110 ~ ~
execute if entity @s[scores={3layer=12}] run tp @s ~120 ~ ~
execute if entity @s[scores={3layer=13}] run tp @s ~130 ~ ~
execute if entity @s[scores={3layer=14}] run tp @s ~140 ~ ~
execute if entity @s[scores={3layer=15}] run tp @s ~150 ~ ~
execute if entity @s[scores={3layer=16}] run tp @s ~160 ~ ~
execute if entity @s[scores={3layer=17}] run tp @s ~170 ~ ~
execute if entity @s[scores={3layer=18}] run tp @s ~180 ~ ~
execute if entity @s[scores={3layer=19}] run tp @s ~190 ~ ~
execute if entity @s[scores={3layer=20}] run tp @s ~200 ~ ~
execute if entity @s[scores={3layer=21}] run tp @s ~210 ~ ~
execute if entity @s[scores={3layer=22}] run tp @s ~220 ~ ~
execute if entity @s[scores={3layer=23}] run tp @s ~230 ~ ~
execute if entity @s[scores={3layer=24}] run tp @s ~240 ~ ~
execute if entity @s[scores={3layer=25}] run tp @s ~250 ~ ~
