execute if entity @s[scores={1layer=1}] run scriptevent lumetas:property 1layer=1
execute if entity @s[scores={1layer=2}] run scriptevent lumetas:property 1layer=2
execute if entity @s[scores={1layer=3}] run scriptevent lumetas:property 1layer=3
execute if entity @s[scores={1layer=4}] run scriptevent lumetas:property 1layer=4
execute if entity @s[scores={1layer=5}] run scriptevent lumetas:property 1layer=5
execute if entity @s[scores={1layer=6}] run scriptevent lumetas:property 1layer=6
execute if entity @s[scores={1layer=7}] run scriptevent lumetas:property 1layer=7
execute if entity @s[scores={1layer=8}] run scriptevent lumetas:property 1layer=8

execute if entity @s[scores={2layer=1}] run scriptevent lumetas:property 2layer=1
execute if entity @s[scores={2layer=2}] run scriptevent lumetas:property 2layer=2
execute if entity @s[scores={2layer=3}] run scriptevent lumetas:property 2layer=3
execute if entity @s[scores={2layer=4}] run scriptevent lumetas:property 2layer=4
execute if entity @s[scores={2layer=5}] run scriptevent lumetas:property 2layer=5
execute if entity @s[scores={2layer=6}] run scriptevent lumetas:property 2layer=6
execute if entity @s[scores={2layer=7}] run scriptevent lumetas:property 2layer=7
execute if entity @s[scores={2layer=8}] run scriptevent lumetas:property 2layer=8
execute if entity @s[scores={2layer=9}] run scriptevent lumetas:property 2layer=9
execute if entity @s[scores={2layer=10}] run scriptevent lumetas:property 2layer=10
execute if entity @s[scores={2layer=11}] run scriptevent lumetas:property 2layer=11
execute if entity @s[scores={2layer=12}] run scriptevent lumetas:property 2layer=12
execute if entity @s[scores={2layer=13}] run scriptevent lumetas:property 2layer=13
execute if entity @s[scores={2layer=14}] run scriptevent lumetas:property 2layer=14
execute if entity @s[scores={2layer=15}] run scriptevent lumetas:property 2layer=15
execute if entity @s[scores={2layer=16}] run scriptevent lumetas:property 2layer=16

execute if entity @s[scores={3layer=1}] run scriptevent lumetas:property 3layer=1
execute if entity @s[scores={3layer=2}] run scriptevent lumetas:property 3layer=2
execute if entity @s[scores={3layer=3}] run scriptevent lumetas:property 3layer=3
execute if entity @s[scores={3layer=4}] run scriptevent lumetas:property 3layer=4
execute if entity @s[scores={3layer=5}] run scriptevent lumetas:property 3layer=5
execute if entity @s[scores={3layer=6}] run scriptevent lumetas:property 3layer=6
execute if entity @s[scores={3layer=7}] run scriptevent lumetas:property 3layer=7
execute if entity @s[scores={3layer=8}] run scriptevent lumetas:property 3layer=8
execute if entity @s[scores={3layer=9}] run scriptevent lumetas:property 3layer=9
execute if entity @s[scores={3layer=10}] run scriptevent lumetas:property 3layer=10
execute if entity @s[scores={3layer=11}] run scriptevent lumetas:property 3layer=11
execute if entity @s[scores={3layer=12}] run scriptevent lumetas:property 3layer=12
execute if entity @s[scores={3layer=13}] run scriptevent lumetas:property 3layer=13
execute if entity @s[scores={3layer=14}] run scriptevent lumetas:property 3layer=14
execute if entity @s[scores={3layer=15}] run scriptevent lumetas:property 3layer=15
execute if entity @s[scores={3layer=16}] run scriptevent lumetas:property 3layer=16
execute if entity @s[scores={3layer=17}] run scriptevent lumetas:property 3layer=17
execute if entity @s[scores={3layer=18}] run scriptevent lumetas:property 3layer=18
execute if entity @s[scores={3layer=19}] run scriptevent lumetas:property 3layer=19
execute if entity @s[scores={3layer=20}] run scriptevent lumetas:property 3layer=20
execute if entity @s[scores={3layer=21}] run scriptevent lumetas:property 3layer=21
execute if entity @s[scores={3layer=22}] run scriptevent lumetas:property 3layer=22
execute if entity @s[scores={3layer=23}] run scriptevent lumetas:property 3layer=23
execute if entity @s[scores={3layer=24}] run scriptevent lumetas:property 3layer=24
execute if entity @s[scores={3layer=25}] run scriptevent lumetas:property 3layer=25
